/** Lista fixa dos 30 bancos mais usados no Brasil (código COMPE + nome), pra facilitar o cadastro. */
export type BancoPreset = { codigo: string; nome: string };

export const BANCOS_BRASILEIROS: BancoPreset[] = [
  { codigo: "260", nome: "Nubank" },
  { codigo: "341", nome: "Itaú Unibanco" },
  { codigo: "001", nome: "Banco do Brasil" },
  { codigo: "237", nome: "Bradesco" },
  { codigo: "104", nome: "Caixa Econômica Federal" },
  { codigo: "033", nome: "Santander" },
  { codigo: "077", nome: "Banco Inter" },
  { codigo: "336", nome: "C6 Bank" },
  { codigo: "380", nome: "PicPay" },
  { codigo: "323", nome: "Mercado Pago" },
  { codigo: "290", nome: "PagBank" },
  { codigo: "208", nome: "BTG Pactual" },
  { codigo: "212", nome: "Banco Original" },
  { codigo: "735", nome: "Neon" },
  { codigo: "197", nome: "Stone" },
  { codigo: "756", nome: "Sicoob" },
  { codigo: "748", nome: "Sicredi" },
  { codigo: "041", nome: "Banrisul" },
  { codigo: "070", nome: "BRB" },
  { codigo: "422", nome: "Banco Safra" },
  { codigo: "623", nome: "Banco Pan" },
  { codigo: "655", nome: "Banco Votorantim" },
  { codigo: "318", nome: "Banco BMG" },
  { codigo: "746", nome: "Banco Modal" },
  { codigo: "218", nome: "Banco BS2" },
  { codigo: "102", nome: "XP Investimentos" },
  { codigo: "025", nome: "Banco Alfa" },
  { codigo: "021", nome: "Banestes" },
  { codigo: "003", nome: "Banco da Amazônia" },
  { codigo: "004", nome: "Banco do Nordeste" },
].sort((a, b) => a.nome.localeCompare(b.nome, "pt-BR"));
